name: Java CI

on:
  push:
    branches:
      - master
      - develop
      - develop-2.1
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Central Repository
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          gpg-passphrase: OSSRH_GPG_PASSPHRASE

      - name: Publish to Central Repository
        run: mvn deploy -P release
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          OSSRH_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}