name: Java CI

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'brapi-java-client/README.md'
      - 'brapi-java-model/README.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'


      - name: Write Maven settings.xml with credentials
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.1"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>central</id>
                <username>${{ secrets.MAVEN_CENTRAL_UN }}</username>
                <password>${{ secrets.MAVEN_CENTRAL_PW }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Import GPG key
        run: |
          echo "${{ secrets.OSSRH_GPG_PRIVATE_KEY }}" | gpg --batch --yes --import
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "pinentry-mode loopback" > ~/.gnupg/gpg.conf
          gpgconf --kill gpg-agent
          gpgconf --launch gpg-agent

      - name: Set GPG_TTY
        run: |
          export GPG_TTY=$(tty)
          echo "GPG_TTY=$GPG_TTY" >> $GITHUB_ENV

      - name: Publish package
        run: mvn --batch-mode -P release deploy -DskipTests -Dgpg.passphrase=${{ secrets.OSSRH_GPG_PASSPHRASE }}
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_UN }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PW }}